version: '3'
services:
    web:
        container_name: web
        image: registry:5000/app_web
        build:
          context: client
        ports:
         - "80:80"
        networks:
          - net
    server:
        container_name: server
        image: registry:5000/app_server
        build:
            context: jenkins-ansible/web
        ports:
         - "80:80"
        networks:
          - net
    registry:
        container_name: registry
        image: registry
        ports:
         - "5000:5000"
        networks:
         - net
        
