version: '3'
services:
    web:
        container_name: web
        image: app_web
        build:
          context: client
        ports:
         - "80:80"
        networks:
          - app
    server:
        container_name: server
        image: app_server
        build:
            context: server
        ports:
         - "9000:9000"
        networks:
         - app
    registry:
        container_name: registry
        image: registry
        ports:
         - "5000:5000"
        networks:
         - app
networks:
    app:
          
